name: Build Linux and Mac distributables of application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make

  build-mac:
    runs-on: "macos-11"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make
