# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
  
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make

    - name: Upload build artefacts
      uses: actions/upload-artifact@v3
      with:
        name: app-zip-ubuntu
        path: out/make/zip/linux/x64/task_keeper_window-linux-x64-1.0.0.zip
        retention-days: 1

  build-windows:
    runs-on: "windows-2019"

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make

    - name: Upload build artefacts
      uses: actions/upload-artifact@v3
      with:
        name: app-zip-windows
        path: "out\\make\\squirrel.windows\\x64\\task_keeper_window-1.0.0 Setup.exe"
        retention-days: 1
