name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: "ubuntu-22.04"
  
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      
    - name: Build
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make

    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: app-zip-ubuntu
        path: out/make/zip/linux
        retention-days: 1

  build-mac:
    runs-on: "macos-15"

    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      
    - name: Build
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make

    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: app-zip-mac
        path: out/make/zip/darwin
        retention-days: 1
