name: Build Linux and Mac distributables of application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
  
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make

    - name: Upload build artefacts
      uses: actions/upload-artifact@v3
      with:
        name: app-zip-ubuntu
        path: out/make/zip/linux/x64/g-apps-navigator-linux-x64-1.0.0.zip
        retention-days: 1

  build-mac:
    runs-on: "macos-latest"

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run make

    - name: Upload build artefacts
      uses: actions/upload-artifact@v3
      with:
        name: app-zip-mac
        path: out/make/zip/
        retention-days: 1
